name: Pipeline_Examen
on:
  push:
    branches:
      - feat_pipeline 

jobs: 
  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repositorio en el runner (Github)
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Ajusta a tu versión

      - name: Instalar dependencias
        run: npm install
        
      - name: Compilar y empaquetar
        run: |
          npm run build

      - name: Upload build output
        uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: ${{ github.workspace }}/.next
          include-hidden-files: true

      - name: Validando existencia de proyecto en SonarCloud
        id: validateProjectOnSonar
        run: |
          #pwd
          #ls -R
          set +e
          curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=inictel2025' -d 'visibility=public'
          if [ $? -ne 0 ]; then
            echo "Proyecto ya existe en Sonarcloud"
            echo "::set-output name=proyectoExiste::1"
          else
            echo "Proyecto ${{ github.event.repository.name }} creado exitosamente en Sonarcloud"
            echo "Se establece rama main como rama por defecto"
            curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{ github.event.repository.name }}'
          fi
          set -e
      - name: Analizar codigo con SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=${{ github.event.repository.name }} \
            -Dsonar.organization=inictel2025 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.branch.name=main

      - name: Validando resultado de SonarCloud
        run: |
          issueValidate=$(curl -s -X GET -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/issues/search?branch=main&componentKeys=pet-clinic-&facets=severities' | jq '.facets[0].values[1].count')
          if [ "$issueValidate" -gt 0 ]; then
            echo "Existen problemas en el código, se detiene el pipeline"
          #exit 1
          else
            echo "No existen problemas en el código, se continúa con el pipeline"
          fi
  SCA:
    needs: SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: ${{ github.workspace }}/.next
          include-hidden-files: true

      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        env:
          JAVA_HOME: /opt/jdk
        with:
          project: '${{ github.event.repository.name }}'
          path: '.'
          format: 'ALL'
          out: 'reports'
          args: >
            --failOnCVSS 7
            --enableRetired

      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@master
        with:
          name: dependecy-check-report
          path: ${{ github.workspace }}/reports

#      - name: Validar resultado Dependency Check
#        run: |
#          report="reports/dependency-check-report.json"

#          if [ ! -f "$report" ]; then
#            echo "No se encontró el reporte de Dependency Check. Falla el análisis SCA."
#            exit 1
#          fi

          # Modificado para usar los valores correctos de severidad
#          critical=$(jq '[.dependencies[].vulnerabilities[]? | select(.severity == "high")] | length' "$report")
#          high=$(jq '[.dependencies[].vulnerabilities[]? | select(.severity == "high")] | length' "$report")
#          medium=$(jq '[.dependencies[].vulnerabilities[]? | select(.severity == "moderate")] | length' "$report")

#          echo "Vulnerabilidades críticas/altas: $critical"
#          echo "Vulnerabilidades medias: $medium"

#          if [ "$critical" -gt 0 ] || [ "$high" -gt 0 ] || [ "$medium" -gt 0 ]; then
#            echo "Se encontraron vulnerabilidades Críticas, Altas o Medias en dependencias. Deteniendo el pipeline..."
#            exit 1
#          else
#            echo "No se encontraron vulnerabilidades críticas, altas ni medias. Continuando..."
#          fi

 #--------------------Contruccion de imagen -------------------------------------------

  DockerBuild:
    needs: SCA 
    runs-on: ubuntu-latest
    steps:
      - name: Copiar el código fuente al runner
        uses: actions/checkout@v2

      - name: Descargar el artefacto compilado en el modulo de SAST
        uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: ${{ github.workspace }}/.next
          include-hidden-files: true
    
      - name: Construir la imagen Docker
        run : | 
          docker build --tag vsvu1001/final_pipeline:latest .

      - name : Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Subir imagen Docker en Docker Hub
        run : | 
          docker push vsvu1001/final_pipeline:latest

# ----------------- Docker Scan ------------------------------------------------
  DockerScan:
    needs: DockerBuild
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código fuente al runner
        uses: actions/checkout@v2
      
      - name : Dockerlogin 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name : Descargar la imagen docker 
        run : | 
          docker pull vsvu1001/final_pipeline:latest

      - name : Ejecutar Docker Scan  -Trivy 
        uses: aquasecurity/trivy-action@master
        with: 
          image-ref: vsvu1001/final_pipeline:latest
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH,MEDIUM'

    